## This is a much bigger dataset than the 3000 PBMC sample, as it contains 160,000 PBMCs (or a version that is down-sampled to 50,000) derived from a CITE-Seq experiment. We run the visualizer using sparse data in the expression field (.X) of an AnnData object as input and the performance is still quite good

 - Data: https://atlas.fredhutch.org/nygc/multimodal-pbmc/
 - Pre-print: https://www.biorxiv.org/content/10.1101/2020.10.12.335331v1.full
 - Cell publication:
https://www.sciencedirect.com/science/article/pii/S0092867421005833#undfig1

In [1]:
import pandas as pd
import numpy as np
from scipy.io import mmread
import scipy.sparse as sparse
import scanpy as sc
from sciviewer import SCIViewer

In [2]:
%load_ext py5
%gui osx
%load_ext autoreload
%autoreload 2

In [3]:
print('DOWNLOADING AND EXTRACTING EXAMPLE DATA')
! mkdir -p ../data

## Full-sized dataset of 160K cells
! wget https://www.dropbox.com/s/5knwop1zs7uaww4/CiteSeqPBMC160K_ProteinAndRNA_merged.h5ad -O ../data/CiteSeqPBMC160K_ProteinAndRNA_merged.h5ad
    
## Sub-sampled datset of 50K cells
! wget https://www.dropbox.com/s/fyusuk61kmnbyv4/CiteSeqPBMC160K_ProteinAndRNA_merged_sub50k.h5ad -O ../data/CiteSeqPBMC160K_ProteinAndRNA_merged_sub50k.h5ad

DOWNLOADING AND EXTRACTING EXAMPLE DATA
--2021-07-08 12:44:41--  https://www.dropbox.com/s/5knwop1zs7uaww4/CiteSeqPBMC160K_ProteinAndRNA_merged.h5ad
Resolving www.dropbox.com (www.dropbox.com)... 162.125.4.18
Connecting to www.dropbox.com (www.dropbox.com)|162.125.4.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/5knwop1zs7uaww4/CiteSeqPBMC160K_ProteinAndRNA_merged.h5ad [following]
--2021-07-08 12:44:41--  https://www.dropbox.com/s/raw/5knwop1zs7uaww4/CiteSeqPBMC160K_ProteinAndRNA_merged.h5ad
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uca2511948d32c77ae80536c9541.dl.dropboxusercontent.com/cd/0/inline/BR4XGmtGM-W531NzVDKI9ePSgV8viPnLL_Pls7a5ewK0RfpfN9jv8X22y9cMw4gjnIGVpsSceeIXi39lmxOcn_ayZIG2WpcddKVv0681Zupwyowb3JZOPwc-NMTUJK-tNDobzdZCNS4dut49jxQpBE2A/file# [following]
--2021-07-08 12:44:41--  https://uca2511948d32c77ae80536c9541.dl.dropboxusercontent.com/cd/

In [3]:
data = sc.read('../data/CiteSeqPBMC160K_ProteinAndRNA_merged.h5ad')

In [4]:
data

AnnData object with n_obs × n_vars = 161764 × 17516
    obs: 'nCount_ADT', 'nFeature_ADT', 'nCount_RNA', 'nFeature_RNA', 'orig.ident', 'lane', 'donor', 'time', 'celltype.l1', 'celltype.l2', 'celltype.l3', 'Phase', 'nCount_SCT', 'nFeature_SCT', 'n_counts'
    var: 'features'
    obsm: 'X_apca', 'X_aumap', 'X_pca', 'X_spca', 'X_umap', 'X_wnn.umap'

In [5]:
data.X

<161764x17516 sparse matrix of type '<class 'numpy.float32'>'
	with 370421313 stored elements in Compressed Sparse Column format>

#### We call SCIViewer using the optional parameter `embedding_name` which indicates we want to use the UMAP computed using the weighted nearest neighbors graph that integrates information from each cell's nearest neighbors to determine how to weight the protein and RNA features

In [6]:
svobj = SCIViewer(data, embedding_name='X_wnn.umap')
svobj.explore_data()

3.4424688816070557 seconds to select and project cells
Selected 2789 cells
Calculating differential expression...
24.778017044067383 seconds to calculate genesums. Sparsity:  True
54.78173899650574 seconds to calculate squared genesums. Sparsity:  True
173.33460211753845 seconds to calculate differential expression. Sparsity:  True
Selected gene Prot_TCR-V-7.2
Min/max expression level for gene Prot_TCR-V-7.2 0.0 5.64773
EXPORTING DATA...
BYE
EXPORTING DATA...
BYE


In [3]:
## Or for down-sampled dataset
data_sub = sc.read('../data/CiteSeqPBMC160K_ProteinAndRNA_merged_sub50k.h5ad')

Observation names are not unique. To make them unique, call `.obs_names_make_unique`.


In [4]:
data_sub

AnnData object with n_obs × n_vars = 50000 × 17516
    obs: 'nCount_ADT', 'nFeature_ADT', 'nCount_RNA', 'nFeature_RNA', 'orig.ident', 'lane', 'donor', 'time', 'celltype.l1', 'celltype.l2', 'celltype.l3', 'Phase', 'nCount_SCT', 'nFeature_SCT', 'n_counts'
    var: 'features'
    obsm: 'X_apca', 'X_aumap', 'X_pca', 'X_spca', 'X_umap', 'X_wnn.umap'

In [5]:
data_sub.X = sparse.csc.csc_matrix(data_sub.X)

In [6]:
svobj = SCIViewer(data_sub, embedding_name='X_wnn.umap')
svobj.explore_data()

1.142807960510254 seconds to select and project cells
Selected 4861 cells
Calculating correlations...
3.190542697906494 seconds to calculate correlations. Sparsity:  True
Selected gene HLA-DRA
Min/max expression level for gene HLA-DRA 0.0 5.3541265
0.5664069652557373 seconds to select and project cells
Selected 850 cells
Calculating differential expression...
0.09165000915527344 seconds to calculate genesums. Sparsity:  True
3.8319427967071533 seconds to calculate squared genesums. Sparsity:  True
7.662507057189941 seconds to calculate differential expression. Sparsity:  True
Selected gene Prot_TCR-V-7.2
Min/max expression level for gene Prot_TCR-V-7.2 0.0 5.5154824
EXPORTING DATA...
BYE


In [3]:
print("LOADING UMAP DATA...")

umap = pd.read_csv('../../sciviewer_data/pbmc_citeseq100K/PBMC100K_RNAandPROTEINmerged_logTP10K.sub50k.joint_umap.tsv',
                   sep='\t', index_col=0)
umap.head()

LOADING UMAP DATA...


UMAP_1    UMAP_2
L3_ACTGTGAGTGGAAATT    9.271340 -0.378436
L5_TCACATTCACATGAAA    8.293193  6.904835
E2L4_TCTCACGCAGAGGAAA -7.722053  3.987209
E2L7_TGATGCAAGGAACGCT -9.115604  3.671707
E2L1_TATTTCGTCAACTACG  7.976065 -7.689341

In [6]:
print("LOADING GENE EXPRESSION DATA...")
matfn = '../../sciviewer_data/pbmc_citeseq100K/PBMC100K_RNAandPROTEINmerged_logTP10K.sub50k.mtx'
#matnf = '../../sciviewer_data/pbmc_citeseq100K/PBMC100K_rnaexpression_logTP10K.sub50k.mtx'
expr_sparse = mmread(matfn)

expr_sparse = sparse.csc_matrix(expr_sparse)
expr_sparse

LOADING GENE EXPRESSION DATA...


<50000x18846 sparse matrix of type '<class 'numpy.float64'>'
	with 114611105 stored elements in Compressed Sparse Column format>

In [7]:
#genesfn = '../../sciviewer_data/pbmc_citeseq100K/PBMC100K_rnaexpression_logTP10K.genes.tsv'
genesfn = '../../sciviewer_data/pbmc_citeseq100K/PBMC100K_RNAandPROTEINmerged_logTP10K.genes.tsv'
genes = list(pd.read_csv(genesfn, sep='\t', header=None)[1])
barcodes = list(pd.read_csv('../data/PBMC100K_rnaexpression_logTP10K.sub50k.barcodes.tsv', sep='\t', header=None)[0])

In [8]:
import sys
sys.path.append('../sciviewer')
from sciviewer import SCIViewer

In [ ]:
# gene and cell names are provided to the gene_names and cell_names attributes since
# those aren't innately part of the sparse data structure

svobj = SCIViewer(umap.values, expr_sparse,
                  gene_names=genes,
                  cell_names=list(umap.index),
                  width=1600, height=800)
svobj.explore_data()

In [21]:
svobj.results_proj_correlation #.sort_values(by='R', ascending=False)

R             P
AL627309.1  0.007597  4.537307e-01
AL669831.5  0.059973  3.218708e-09
LINC00115   0.020225  4.605774e-02
FAM41C      0.031332  1.996065e-03
NOC2L      -0.026795  8.215979e-03
...              ...           ...
AC016588.1       NaN           NaN
FAM83E           NaN           NaN
Z82244.2         NaN           NaN
AP001468.1 -0.011265  2.665696e-01
AP001469.2 -0.019682  5.222168e-02

[20729 rows x 2 columns]

In [23]:
class Gene():
    def __init__(self, n, i, r, p):
        self.name = n
        self.idx = i
        self.r = r
        self.rabs = abs(r)
        self.p = p

for (i,g) in enumerate(svobj.geneNames):
    if (svobj.pearsonsThreshold <= abs(svobj.results_proj_correlation.at[g, 'R'])) and (svobj.results_proj_correlation.at[g, 'P'] <= svobj.pvalueThreshold):
        if g == 'MS4A1':
            print('')
        
        
        gene = Gene(g, i, rs[i], ps[i])
        svobj.sortedGenes.append(gene)

self.sortedGenes.sort(key=lambda x: x.r, reverse=True)

['AL627309.1',
 'AL669831.5',
 'LINC00115',
 'FAM41C',
 'NOC2L',
 'KLHL17',
 'PLEKHN1',
 'AL645608.8',
 'HES4',
 'ISG15',
 'AGRN',
 'C1orf159',
 'TTLL10',
 'TNFRSF18',
 'TNFRSF4',
 'SDF4',
 'B3GALT6',
 'C1QTNF12',
 'AL162741.1',
 'UBE2J2',
 'SCNN1D',
 'ACAP3',
 'PUSL1',
 'INTS11',
 'CPTP',
 'TAS1R3',
 'DVL1',
 'MXRA8',
 'AURKAIP1',
 'CCNL2',
 'MRPL20',
 'AL391244.3',
 'ANKRD65',
 'ATAD3C',
 'ATAD3B',
 'ATAD3A',
 'TMEM240',
 'SSU72',
 'AL645728.1',
 'FNDC10',
 'AL691432.2',
 'MIB2',
 'MMP23B',
 'CDK11B',
 'FO704657.1',
 'SLC35E2B',
 'CDK11A',
 'SLC35E2A',
 'NADK',
 'GNB1',
 'AL109917.1',
 'PRKCZ',
 'AL590822.2',
 'PRKCZ-AS1',
 'FAAP20',
 'SKI',
 'MORN1',
 'RER1',
 'PEX10',
 'PLCH2',
 'PANK4',
 'AL139246.5',
 'TNFRSF14-AS1',
 'TNFRSF14',
 'AL139246.3',
 'FAM213B',
 'MMEL1',
 'TTC34',
 'MEGF6',
 'AL513320.1',
 'TPRG1L',
 'WRAP73',
 'SMIM1',
 'LRRC47',
 'CEP104',
 'DFFB',
 'C1orf174',
 'LINC01134',
 'AJAP1',
 'NPHP4',
 'KCNAB2',
 'CHD5',
 'RPL22',
 'RNF207',
 'ICMT',
 'GPR153',
 'ACOT7',
 

In [20]:
i = 0

for i in range(len(svobj.sortedGenes)):
    if svobj.sortedGenes[i].name == 'MS4A1':
        print(i)
        break
    

svobj.sortedGenes[i].name, svobj.sortedGenes[i].idx, svobj.sortedGenes[i].r, svobj.sortedGenes[i].p

3174


('MS4A1', 8497, -0.6758202446237773, 0.0)

In [25]:
genes_array = np.array(genes)
ind = svobj.renderer.indices
x = np.array(expr_sparse[ind,genes_array=='RPL13']).reshape(-1)
vproj = []
for i in ind:
    vproj.append(svobj.cells[i].proj)     
vproj = np.array(vproj)

from scipy.stats import pearsonr

pearsonr(x, vproj)

(0.7883478498202883, 0.0)

Selected gene TANGO6
Min/max expression level for gene TANGO6 0.0 2.0086
0.3911468982696533 seconds to select and project cells
to
Selected 750 cells
Calculating correlations...
1.1669340133666992 seconds to calculate correlations. Sparsity:  True
Selected gene EHHADH
Min/max expression level for gene EHHADH 0.0 1.9731
Selected gene PPP2R5C
Min/max expression level for gene PPP2R5C 0.0 3.4131
Selected gene DNM3
Min/max expression level for gene DNM3 0.0 3.0198
0.9384839534759521 seconds to select and project cells
Selected 5721 cells
Calculating differential expression...
0.12740206718444824 seconds to calculate genesums. Sparsity:  True
6.167443037033081 seconds to calculate squared genesums. Sparsity:  True
13.277081966400146 seconds to calculate differential expression. Sparsity:  True
Selected gene NKG7
Min/max expression level for gene NKG7 0.0 5.1014
Selected gene GNLY
Min/max expression level for gene GNLY 0.0 6.165
Selected gene KLRD1
Min/max expression level for gene KLRD1 0.0

In [35]:
sortedGenes = []
vproj = []
indices = svobj.renderer.indices
for i in indices:
    vproj.append(svobj.cells[i].proj)

dexpr = svobj.expr[indices, :]
        
vproj = np.array(vproj)



y = vproj
x = dexpr
nrow = vproj.size


yy = y - y.mean()
xm = x.mean(axis=0).A.ravel()
ys = yy / np.sqrt(np.dot(yy, yy))
xs = np.sqrt(np.add.reduceat(x.data**2, x.indptr[:-1]) - nrow*xm*xm)
correl2 = np.add.reduceat(x.data * ys[x.indices], x.indptr[:-1]) / xs

IndexError: index 20671522 out-of-bounds in add.reduceat [0, 20671522)

In [43]:
indices = svobj.renderer.indices
c = 1000

y = np.array(expr_sparse[indices,c].todense()).reshape(-1)
x = expr_sparse[indices, :]
nrow = x.shape[0]

yy = y - y.mean()
xm = x.mean(axis=0).A.ravel()
ys = yy / np.sqrt(np.dot(yy, yy))
xs = np.sqrt(np.add.reduceat(x.data**2, x.indptr[:-1]) - nrow*xm*xm)
correl2 = np.add.reduceat(x.data * ys[x.indices], x.indptr[:-1]) / xs


IndexError: index 20671522 out-of-bounds in add.reduceat [0, 20671522)

In [44]:
y

array([0.     , 0.     , 1.0038 , ..., 0.     , 0.81372, 0.     ])

In [45]:
y.shape

(12073,)

In [46]:
x

<12073x20729 sparse matrix of type '<class 'numpy.float64'>'
	with 20671522 stored elements in Compressed Sparse Column format>

In [100]:
f1 = 0
t1 = expr_sparse.shape[1]

#f1 = 19127
#t1 = expr_sparse.shape[1]

c = 1000
nrow = x.shape[0]
num_indices = 1000
#indices = np.random.choice(nrow, size=num_indices)
indices = svobj.renderer.indices

y_new = np.array(expr_sparse[indices,c].todense()).reshape(-1)
x_new = expr_sparse[indices, f1:t1]

tokeep = np.array(x_new.sum(axis=0)!=0).reshape(-1)
x_new = x_new[:, tokeep]

yy_new = y_new - y_new.mean()
xm_new = x_new.mean(axis=0).A.ravel()
ys_new = yy_new / np.sqrt(np.dot(yy_new, yy_new))
xs_new = np.sqrt(np.add.reduceat(x_new.data**2, x_new.indptr[:-1]) - nrow*xm_new*xm_new)
correl_new = np.add.reduceat(x_new.data * ys_new[x_new.indices], x_new.indptr[:-1]) / xs_new

In [99]:
np.indices(tokeep)

TypeError: only integer scalar arrays can be converted to a scalar index

In [91]:
z = np.array(x_new.sum(axis=0)).reshape(-1)

In [92]:
pd.Series(z>0).value_counts()

True     18190
False      933
dtype: int64

In [71]:
expr_sparse[indices, 19120:19139].sum(axis=0)

matrix([[ 0.     ,  0.     ,  9.08906,  0.     ,  0.     ,  0.     ,
          2.65494,  5.80211,  0.     ,  0.     ,  9.71714,  0.85561,
          2.31432, 10.93949,  0.     ,  0.     ,  0.     ,  1.67147,
          0.     ]])

In [57]:
expr_sparse.shape[1]

20729

In [52]:
x_new

<12073x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1329673 stored elements in Compressed Sparse Column format>

In [33]:
sortedGenes = []
vproj = []
indices = svobj.renderer.indices
for i in indices:
    vproj.append(svobj.cells[i].proj)

dexpr = svobj.expr[indices, :]
        
vproj = np.array(vproj)


n = vproj.size
if svobj.sparse:
    # based on https://www.javaer101.com/en/article/18344934.html
    yy = vproj - vproj.mean()
    xm = dexpr.mean(axis=0).A.ravel()
    ys = yy / np.sqrt(np.dot(yy, yy))
    xs = np.sqrt(np.add.reduceat(dexpr.data**2, dexpr.indptr[:-1]) - n*xm*xm)
    rs = np.add.reduceat(dexpr.data * ys[dexpr.indices], dexpr.indptr[:-1]) / xs

IndexError: index 883873 out-of-bounds in add.reduceat [0, 883873)

In [36]:
np.add.reduceat(dexpr.data**2, dexpr.indptr[:-3])

IndexError: index 3157402 out-of-bounds in add.reduceat [0, 3157402)

In [34]:
np.add.reduceat(dexpr.data**2, dexpr.indptr[:-1])

IndexError: index 3157402 out-of-bounds in add.reduceat [0, 3157402)

In [32]:
dexpr.data.shape

(3157402,)

In [33]:
dexpr.indptr[:-1]

array([      0,       4,      65, ..., 3157402, 3157402, 3157402],
      dtype=int32)

In [22]:
yy.shape

(1520,)

In [23]:
dexpr

<1520x20729 sparse matrix of type '<class 'numpy.float64'>'
	with 3157402 stored elements in Compressed Sparse Column format>

In [24]:
vproj.shape

(1520,)

In [19]:
dexpr

<1520x20729 sparse matrix of type '<class 'numpy.float64'>'
	with 3157402 stored elements in Compressed Sparse Column format>

In [22]:
svobj.umap

array([[ -9.28711415,  -4.05189541],
       [ -7.82039547,  -2.2564905 ],
       [ -0.96361929,  15.92775937],
       ...,
       [  2.60810637,   3.90169188],
       [  2.56579613, -10.09597281],
       [  2.27859306,  -9.86814479]])

In [29]:
np.array(svobj.renderer.indices)[::-1]

array([49986, 49931, 49860, 49782, 49651, 49613, 49555, 49546, 49471,
       49447, 49445, 49389, 49335, 49212, 49167, 49127, 48865, 48846,
       48661, 48660, 48462, 48352, 48337, 48276, 47849, 47787, 47735,
       47593, 47569, 47531, 47455, 47378, 47360, 47247, 47029, 46956,
       46820, 46787, 46734, 46654, 46576, 46531, 46307, 46117, 46034,
       45792, 45759, 45714, 45525, 45447, 45413, 45293, 45281, 45225,
       45196, 45054, 44991, 44921, 44872, 44856, 44809, 44705, 44630,
       44423, 44386, 44340, 44232, 44218, 44043, 43779, 43612, 43543,
       43447, 43386, 43319, 43308, 43199, 43197, 43186, 43156, 43143,
       43004, 42857, 42741, 42677, 42643, 42349, 42300, 42162, 42156,
       42104, 41839, 41824, 41761, 41700, 41449, 41445, 41441, 41409,
       41369, 41339, 41312, 41264, 41059, 41051, 40969, 40843, 40836,
       40764, 40744, 40683, 40565, 40501, 40476, 40457, 40415, 40391,
       40358, 40211, 40148, 39983, 39924, 39870, 39799, 39772, 39706,
       39614, 39519,

In [8]:
# gene and cell names are provided to the gene_names and cell_names attributes since
# those aren't innately part of the sparse data structure

svobj = SCIViewer(umap, expr_sparse, gene_names=genes,
                    cell_names=barcodes)
svobj.explore_data()

2.1275150775909424 seconds to select and project cells
Selected 2414 cells
Calculating differential expression...
19.73544430732727 seconds to calculate genesums. Sparsity:  True
35.344122886657715 seconds to calculate squared genesums. Sparsity:  True


array(['E2L1_ATCCTATAGAGATGCC', 'L5_TTCAATCCACGGTGCT',
       'L1_CGATCGGGTGATACCT', ..., 'L4_TTTGACTTCTCAAAGC',
       'L4_CCTTTGGTCTAACGCA', 'L3_TTACCGCAGCCGAATG'], dtype='<U21')

In [9]:
3

109.99490594863892 seconds to calculate differential expression. Sparsity:  True


3

In [10]:
2

2

Selected gene CD74
Min/max expression level for gene CD74 0.0 5.442417710521793
Selected gene HLA-DRA
Min/max expression level for gene HLA-DRA 0.0 5.455321115357702
1.9083669185638428 seconds to select and project cells
Selected 366 cells
Calculating differential expression...
44.587007999420166 seconds to calculate differential expression. Sparsity:  True
Selected gene MZB1
Min/max expression level for gene MZB1 0.0 4.691347882229143
1.511157751083374 seconds to select and project cells
Selected 2228 cells
Calculating differential expression...
53.11885690689087 seconds to calculate differential expression. Sparsity:  True
EXPORTING DATA...
BYE


In [8]:
## This attribute get updated in real time whenever cells are selected

svobj.selected_cells.head()

index         cell_name  projection
0      0  AAACATACACCCAA-1    0.850499
1      7  AAACATTGCTTCGC-1    0.141245
2     12  AAACCGTGCCCAAA-1    0.635838
3     13  AAACCGTGCGATAC-1    0.859967
4     15  AAACCGTGTCACCC-1    0.808978

In [11]:
## This gets updated in real time when cells are selected in directional mode
svobj.results_proj_correlation.sort_values(by='P').head()

R              P
FOS     0.438860  5.278833e-255
DUSP1   0.428832  2.464365e-242
S100A4  0.410756  1.485400e-220
LTB     0.390538  9.784411e-198
MALAT1 -0.346522  2.575518e-153

EXPORTING DATA...
BYE


In [10]:
## This gets updated in real time when cells are selected in differential mode
svobj.results_diffexpr.sort_values(by='P').head()

T    P
JUNB    -56.351577  0.0
RPS8    -57.105766  0.0
COTL1   -46.026753  0.0
PIK3IP1 -53.734194  0.0
KLRD1    43.096151  0.0

0.7509219646453857 seconds to select and project cells
Selected 2912 cells
Calculating correlations...
2.000452995300293 seconds to calculate correlations. Sparsity:  True
Selected gene GNLY
Min/max expression level for gene GNLY 0.0 6.0092
Selected gene CD8B
Min/max expression level for gene CD8B 0.0 4.8472
0.6916131973266602 seconds to select and project cells
Selected 2378 cells
Calculating correlations...
1.4387142658233643 seconds to calculate correlations. Sparsity:  True
Selected gene FOS
Min/max expression level for gene FOS 0.0 4.8013
1.1787519454956055 seconds to select and project cells
Selected 5441 cells
Calculating correlations...
1.5225191116333008 seconds to calculate correlations. Sparsity:  True
Selected gene FOS
Min/max expression level for gene FOS 0.0 4.8013


## You can re-run the analysis using dense data and see how much slower it is

In [12]:
expr_dense = pd.DataFrame(expr_sparse.todense(), columns=genes, index=barcodes)

In [13]:
expr_dense.iloc[:5, :5]

LINC00115  FAM41C  NOC2L  KLHL17  PLEKHN1
AAACATACACCCAA-1        0.0     0.0    0.0     0.0      0.0
AAACATACCCCTCA-1        0.0     0.0    0.0     0.0      0.0
AAACATACCGGAGA-1        0.0     0.0    0.0     0.0      0.0
AAACATACTCTTCA-1        0.0     0.0    0.0     0.0      0.0
AAACATACTGGATC-1        0.0     0.0    0.0     0.0      0.0

In [14]:
expr_dense.shape

(52899, 12563)

In [16]:
svobj_dense = SCIViewer(umap, expr_dense)
svobj_dense.explore_data()

0.9585070610046387 seconds to select and project cells
Selected 5328 cells
Calculating differential expression...
8.030466079711914 seconds to calculate genesums. Sparsity:  False
26.470013856887817 seconds to calculate squared genesums. Sparsity:  False


/Users/dylankotliar/miniconda3/envs/sciviewer/lib/python3.8/site-packages/sciviewer/sciviewer.py:572: RuntimeWarning: invalid value encountered in sqrt
  remainder_stds = np.sqrt((self.gene_sqsum - selected_stds - (remainder_N*remainder_means**2)) / (remainder_N -1))


63.93354320526123 seconds to calculate differential expression. Sparsity:  False
Selected gene NKG7
Min/max expression level for gene NKG7 0.0 5.463
Selected gene GNLY
Min/max expression level for gene GNLY 0.0 6.0092
Selected gene CCL5
Min/max expression level for gene CCL5 0.0 5.743
0.7948040962219238 seconds to select and project cells
Selected 2194 cells
Calculating correlations...


/Users/dylankotliar/miniconda3/envs/sciviewer/lib/python3.8/site-packages/sciviewer/sciviewer.py:613: RuntimeWarning: invalid value encountered in true_divide
  rs = np.dot(DP, DO) / np.sqrt(np.sum(DO ** 2, 0) * np.sum(DP ** 2))


13.287477016448975 seconds to calculate correlations. Sparsity:  False
Selected gene S100A4
Min/max expression level for gene S100A4 0.0 5.2892
EXPORTING DATA...
BYE
